// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: vns/vns.proto

package vns

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  int32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Lat float64 `protobuf:"fixed64,2,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lng float64 `protobuf:"fixed64,3,opt,name=Lng,proto3" json:"Lng,omitempty"`
}

func (x *Stop) Reset() {
	*x = Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vns_vns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_vns_vns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_vns_vns_proto_rawDescGZIP(), []int{0}
}

func (x *Stop) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Stop) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Stop) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type OptimizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stops  []*Stop   `protobuf:"bytes,1,rep,name=Stops,proto3" json:"Stops,omitempty"`
	Matrix []float64 `protobuf:"fixed64,2,rep,packed,name=Matrix,proto3" json:"Matrix,omitempty"`
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vns_vns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vns_vns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_vns_vns_proto_rawDescGZIP(), []int{1}
}

func (x *OptimizeRequest) GetStops() []*Stop {
	if x != nil {
		return x.Stops
	}
	return nil
}

func (x *OptimizeRequest) GetMatrix() []float64 {
	if x != nil {
		return x.Matrix
	}
	return nil
}

type OptimizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stops []*Stop `protobuf:"bytes,1,rep,name=Stops,proto3" json:"Stops,omitempty"`
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vns_vns_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vns_vns_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_vns_vns_proto_rawDescGZIP(), []int{2}
}

func (x *OptimizeResponse) GetStops() []*Stop {
	if x != nil {
		return x.Stops
	}
	return nil
}

var File_vns_vns_proto protoreflect.FileDescriptor

var file_vns_vns_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x6e, 0x73, 0x2f, 0x76, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x76, 0x6e, 0x73, 0x22, 0x3a, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x4c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x4c, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4c, 0x6e, 0x67,
	0x22, 0x4a, 0x0a, 0x0f, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x76, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x05, 0x53,
	0x74, 0x6f, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x22, 0x33, 0x0a, 0x10,
	0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x76, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x70,
	0x73, 0x32, 0x4c, 0x0a, 0x0f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x56, 0x4e, 0x53, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65,
	0x12, 0x14, 0x2e, 0x76, 0x6e, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x76, 0x6e, 0x73, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6d, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69,
	0x67, 0x2d, 0x65, 0x6c, 0x67, 0x74, 0x2f, 0x74, 0x73, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vns_vns_proto_rawDescOnce sync.Once
	file_vns_vns_proto_rawDescData = file_vns_vns_proto_rawDesc
)

func file_vns_vns_proto_rawDescGZIP() []byte {
	file_vns_vns_proto_rawDescOnce.Do(func() {
		file_vns_vns_proto_rawDescData = protoimpl.X.CompressGZIP(file_vns_vns_proto_rawDescData)
	})
	return file_vns_vns_proto_rawDescData
}

var file_vns_vns_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vns_vns_proto_goTypes = []interface{}{
	(*Stop)(nil),             // 0: vns.Stop
	(*OptimizeRequest)(nil),  // 1: vns.OptimizeRequest
	(*OptimizeResponse)(nil), // 2: vns.OptimizeResponse
}
var file_vns_vns_proto_depIdxs = []int32{
	0, // 0: vns.OptimizeRequest.Stops:type_name -> vns.Stop
	0, // 1: vns.OptimizeResponse.Stops:type_name -> vns.Stop
	1, // 2: vns.BasicVNSService.Optimize:input_type -> vns.OptimizeRequest
	2, // 3: vns.BasicVNSService.Optimize:output_type -> vns.OptimizeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vns_vns_proto_init() }
func file_vns_vns_proto_init() {
	if File_vns_vns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vns_vns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vns_vns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptimizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vns_vns_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptimizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vns_vns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vns_vns_proto_goTypes,
		DependencyIndexes: file_vns_vns_proto_depIdxs,
		MessageInfos:      file_vns_vns_proto_msgTypes,
	}.Build()
	File_vns_vns_proto = out.File
	file_vns_vns_proto_rawDesc = nil
	file_vns_vns_proto_goTypes = nil
	file_vns_vns_proto_depIdxs = nil
}
